### ISSUE TITLE
损失函数的问题

### ISSUE THREAD

**Issue by HelpFireCode** [Linda230/AFNC#1]
请问为什么在训练策略为adaptive_elimination时，损失函数要用交叉熵呢？这个我看论文和代码都没理解到您想表达的意思……😁

**Comment by Linda230** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你好，这个是对比损失函数的定义，你可以尝试通过数学变换，一步一步的推导，最后可以转化为交叉熵的形式，但是我使用的对比损失函数。
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                徐玲玲
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年02月28日 16:40
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              [Linda230/AFNC] 损失函数的问题 (Issue #1)
        
      
    
  
  
请问为什么在训练策略为adaptive_elimination时，损失函数要用交叉熵呢？这个我看论文和代码都没理解到您想表达的意思……😁

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by HelpFireCode** [comment]
好的，谢谢您，我再看看。


| |
李豪
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年2月28日 16:49 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Linda230/AFNC] 损失函数的问题 (Issue #1) |







font{
line-height: 1.6;
}
ul,ol{
padding-left: 20px;
list-style-position: inside;
}



你好，这个是对比损失函数的定义，你可以尝试通过数学变换，一步一步的推导，最后可以转化为交叉熵的形式，但是我使用的对比损失函数。

















徐玲玲




***@***.***











---- 回复的原邮件 ----





发件人


***@***.***>





发送日期


2024年02月28日 16:40




收件人




***@***.***>






抄送人



***@***.***>






主题


[Linda230/AFNC] 损失函数的问题 (Issue #1)





请问为什么在训练策略为adaptive_elimination时，损失函数要用交叉熵呢？这个我看论文和代码都没理解到您想表达的意思……😁
